#!/bin/bash

# ------------------------------------------------------------
# easy to use start and stop pipeline
# 
# Autor: Oliver Maurhart, <oliver.maurhart@ait.ac.at>
#
# Copyright (C) 2016 AIT Austrian Institute of Technology
# AIT Austrian Institute of Technology GmbH
# Donau-City-Strasse 1 | 1220 Vienna | Austria
# http://www.ait.ac.at
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation version 2.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, 
# Boston, MA  02110-1301, USA.
# ------------------------------------------------------------


export TEST_BASE="@CMAKE_BINARY_DIR@"

mkdir -p ${TEST_BASE}/log &> /dev/null
rm -rf ${TEST_BASE}/log/*

qkd-pipeline --log ${TEST_BASE}/log start ${TEST_BASE}/test/test-data/simulator/alice.xml
qkd-pipeline --log ${TEST_BASE}/log start ${TEST_BASE}/test/test-data/simulator/bob.xml
