#!/bin/sh

# ------------------------------------------------------------
# prerm
#
# pre removal script run
#
# Author: Oliver Maurhart, <oliver.maurhart@ait.ac.at>
#
# Copyright (C) 2012-2015 AIT Austrian Institute of Technology
# AIT Austrian Institute of Technology GmbH
# Donau-City-Strasse 1 | 1220 Vienna | Austria
# http://www.ait.ac.at
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation version 2.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, 
# Boston, MA  02110-1301, USA.
# ------------------------------------------------------------


# tweak services depending on sysv or systemd
if [ `cat /proc/1/comm` = 'init' ]; then
    # sysv
    /etc/init.d/qkd-dbus stop 
    update-rc.d qkd-dbus remove
    rm -f /run/dbus/qkd-dbus.pid
fi
if [ `cat /proc/1/comm` = 'systemd' ]; then
    # systemd
    systemctl stop qkd-dbus
    systemctl disable qkd-dbus
    systemctl daemon-reload
fi


